version: '3.7'
services:
  case:
    container_name: deep-case
    image: deepf/deepcase:main
    networks:
      - network
    ports:
    - "3007:3007"
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts: ['host.docker.internal:host-gateway']
    environment:
      DEEPLINKS_HASURA_PATH: '${DEEPLINKS_HASURA_PATH}'
      DEEPLINKS_HASURA_SSL: '${DEEPLINKS_HASURA_SSL}'
      DEEPLINKS_HASURA_SECRET: '${DEEPLINKS_HASURA_SECRET}'
      NEXT_PUBLIC_DEEPLINKS_SERVER: '${NEXT_PUBLIC_DEEPLINKS_SERVER}'
      NEXT_PUBLIC_ENGINES: '${NEXT_PUBLIC_ENGINES}'
      NEXT_PUBLIC_ENGINES_ROUTE: '${NEXT_PUBLIC_ENGINES_ROUTE}'
      NEXT_PUBLIC_DISABLE_CONNECTOR: '${NEXT_PUBLIC_DISABLE_CONNECTOR}'
      NEXT_PUBLIC_GQL_PATH: '${NEXT_PUBLIC_GQL_PATH}'
      NEXT_PUBLIC_GQL_SSL: '${NEXT_PUBLIC_GQL_SSL}'
      NEXT_PUBLIC_DEEPLINKS_URL: '${NEXT_PUBLIC_DEEPLINKS_URL}'
      DOCKER: 1
      PORT: '${DEEPCASE_PORT}'
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
networks:
  network:
    name: deep-network
    driver: bridge
